### ISSUE TITLE
Implement path in load_csv_to_df() 

### ISSUE THREAD

**Issue by cmhawkins** [NCATComp410/comp410_summer2020#10]
`# path`
`#    Starting path location to begin the search`
`#`

**Comment by claesmk** [comment]
Here is a hint - https://docs.python.org/3/library/os.html - check out os.walk()

**Comment by claesmk** [comment]
Hi @cmhawkins for this function,  the intent is for the user to have a specific directory where there csv files are stored. In the cloned repository after you run the demo.py script, you will have a default data directory that looks like this:

```
comp410_summer2020 % find data -name "*.csv" -print
data/flights/flights.csv
data/trip_logs/.old_trip_logs.csv
data/trip_logs/invalid_logs.csv
data/trip_logs/trip_logs.csv
data/airlines/airlines.csv
data/airports/airports.csv
```

So, from demo.py, I could call the function like this:
```
 dataframe_list = dt.load_csv_to_df('data', ...)
```

This tells you to begin the search from the data directory located in the current working directory.  I would expect you to find all these CSV files using os.walk(), for example:
```
    for dirpath, dirnames, files in os.walk(path):
        for name in files:
            if name.endswith('.csv'):
                print(os.path.join(dirpath, name))
```

Now, a few things to be careful of

1. You'll need to work with your team because os.walk() has options for following symbolic links - hint this is issue https://github.com/NCATComp410/comp410_summer2020/issues/24
2. A Mac/Linux and Windows have different ways to represent a path.  c:\users\user vs /users/user  - The os library has ways to handle this - os.path.join(), etc.  Make sure any code you write is platform independent!
